# Generated by Django 3.1.3 on 2020-11-11 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'otp',
                'verbose_name_plural': 'otps',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'phone',
                'verbose_name_plural': 'phones',
            },
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=255)),
                ('religion', models.CharField(max_length=255)),
                ('religion_other', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=255)),
                ('job_type_other', models.CharField(max_length=255)),
                ('job_category_health_related', models.CharField(max_length=255)),
                ('clinical_or_nonclinical_job', models.CharField(max_length=255)),
                ('covid_knowledge_before_survey', models.CharField(max_length=255)),
                ('risk_of_covid_exposure', models.CharField(max_length=255)),
                ('know_of_anyone_diagnosed_with_covid', models.CharField(max_length=255)),
                ('know_of_anyone_hospitalized_due_to_covid', models.CharField(max_length=255)),
                ('know_of_anyone_die_due_to_covid', models.CharField(max_length=255)),
                ('know_of_covid_preventive_measures', models.CharField(max_length=255)),
                ('believe_in_facemask_protection', models.CharField(max_length=255)),
                ('believe_in_social_distancing', models.CharField(max_length=255)),
                ('belive_in_hand_washing', models.CharField(max_length=255)),
                ('think_covid_is_gone', models.CharField(max_length=255)),
                ('think_we_need_covid_vaccine', models.CharField(max_length=255)),
                ('think_vaccines_are_safe', models.CharField(max_length=255)),
                ('heard_of_any_covid_candidate_vaccine', models.CharField(max_length=255)),
                ('participate_in_clinical_covid_vaccine_trial', models.CharField(max_length=255)),
                ('reason_not_to_participate_in_clinical_covid_vaccine_trial', models.CharField(max_length=255)),
                ('reason_not_to_participate_other', models.CharField(max_length=255)),
                ('motivation_for_participation', models.CharField(max_length=255)),
                ('route_of_vaccine_administration', models.CharField(max_length=255)),
                ('type_of_vaccine_acceptable', models.CharField(max_length=255)),
                ('phase_of_clinical_trial_to_participate_in', models.CharField(max_length=255)),
                ('country_of_vaccine_influence_your_decision_to_participate', models.CharField(max_length=255)),
                ('preferred_vaccine_continent', models.CharField(max_length=255)),
                ('vaccine_scientists_should_include_ghanaian', models.CharField(max_length=255)),
                ('participate_in_mass_covid_vaccination', models.CharField(max_length=255)),
                ('prepared_to_pay_for_vaccine', models.CharField(max_length=255)),
                ('estimated_vaccine_cost_range', models.CharField(max_length=255)),
                ('vaccine_cost_range', models.CharField(max_length=255)),
                ('origin_of_vaccine_influence_your_decision_to_participate', models.CharField(max_length=255)),
                ('preferred_vaccine_origin', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'responses',
                'verbose_name_plural': 'responses',
            },
        ),
    ]
