# Generated by Django 3.1.3 on 2020-11-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responses',
            old_name='reason_not_to_participate_other',
            new_name='reason_not_to_participate_in_clinical_covid_vaccine_trial_other',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='vaccine_cost_range',
        ),
    ]
