# Generated by Django 3.1.3 on 2020-11-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
