# Generated by Django 3.1.3 on 2020-11-12 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201112_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='responses',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
