# Generated by Django 3.1.3 on 2020-11-11 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201111_0557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'otp', 'verbose_name_plural': 'otps'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'verbose_name': 'phone', 'verbose_name_plural': 'phones'},
        ),
    ]
