# Generated by Django 3.1.3 on 2020-11-11 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201111_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='submitted_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
