# Generated by Django 3.1.3 on 2020-11-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201112_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
