# Generated by Django 3.1.3 on 2020-11-13 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201112_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responses',
            old_name='belive_in_hand_washing',
            new_name='believe_in_hand_washing',
        ),
    ]
