# Generated by Django 3.1.3 on 2020-11-11 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201111_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
